version: '3'
networks:
  mogo-net:
    driver: bridge
services:
  nginx:
    image: nginx
    networks:
      - mogo-net
    ports:
      - "19003:80"
    volumes:
      - ./data/nginx/html:/usr/share/nginx/html
      - ./data/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./data/nginx/conf.d:/etc/nginx/conf.d
      - ./data/nginx/logs:/var/log/nginx
    restart: always
  fluent-bit:
    image: fluent/fluent-bit:1.8.12
    networks:
      - mogo-net
    environment:
      KAFKA_BROKERS: kafka:9092
    ports:
      - 2020:2020
    volumes:
      - ./data/fluent-bit/conf:/fluent-bit/etc/
      - ./data/nginx/logs:/var/log/containers
    depends_on:
      - nginx
      - kafka
    links:
      - kafka
    restart: always
  zookeeper:
    image: zookeeper
    networks:
      - mogo-net
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    expose:
      - 2181
    volumes:
      - ./data/zookeeper/data:/data
      - ./data/zookeeper/datalog:/datalog
  kafka:
    image: bitnami/kafka:2.8.1
    networks:
      - mogo-net
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    expose:
      - 9092
    depends_on:
      - zookeeper
    restart: always
    volumes:
      - ./data/kafka:/bitnami/kafka
  kowl:
    image: rsmnarts/kowl
    networks:
      - mogo-net
    environment:
      KAFKA_BROKERS: kafka:9092
    ports:
      - 19002:8080
    depends_on:
      - kafka
    links:
      - zookeeper
      - kafka
    restart: always
  mysql:
    image: mysql:5.7.24
    networks:
      - mogo-net
    environment:
      MYSQL_ROOT_PASSWORD: shimo
      MYSQL_ROOT_HOST: '%'
    command: [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_general_ci',
        '--port=13306',
        '--init-file=/data/migration/latest.sql',
    ]
    ports:
      - 13306:13306
    volumes:
      - ./scripts/migration:/data/migration
    restart: always
  redis:
    image: redis:5.0.14-alpine
    networks:
      - mogo-net
    expose:
      - 6380
    restart: always
    command: [ '--port 6380' ]
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    networks:
      - mogo-net
    environment:
      CLICKHOUSE_USER: root
      CLICKHOUSE_PASSWORD: shimo
    expose:
      - 9000
    ports:
      - "8123:8123"
    volumes:
      - ./data/clickhouse/database:/var/lib/clickhouse
      - ./data/clickhouse/logs:/var/log
      - ./data/clickhouse/conf/users.xml:/etc/clickhouse-server/users.xml
    restart: always
    links:
      - kafka
    depends_on:
      - kafka
  api:
    image: sevennt/mogo:master
    networks:
      - mogo-net
    environment:
      EGO_CONFIG_PATH: /mogo/config/docker.toml
      EGO_LOG_WRITER: stderr
    ports:
      - "19001:19001"
    depends_on:
      - mysql
      - redis
      - clickhouse
      - fluent-bit
      - kafka
    links:
      - mysql
      - redis
      - clickhouse
      - kafka
    restart: always
    volumes:
      - ./data/mogo/config:/mogo/config
    command: [ '/bin/sh', '-c', './bin/mogo -job install && ./bin/mogo' ]
