name: docs-apis

on:
  push:
    branches:
      - 'master'

jobs:
  updateAPI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.21.1'
      - run: go version
      - name: install eapi
        id: eapi
        run: |
          export PATH=$(go env GOPATH)/bin:$PATH
          go version 
          go install github.com/gotomicro/eapi/cmd/eapi@v0.4.6
          eapi --config eapi.yaml
      - name: install redoc
        run: npm i -g redoc-cli
      - name: gen HTML
        run: |
          redoc-cli bundle ./api/docs/swagger.json ./api/docs/index.html
          mv redoc-static.html ./api/docs/index.html
      - name: install obsutil
        run: wget https://obs-community.obs.cn-north-1.myhuaweicloud.com/obsutil/current/obsutil_linux_amd64.tar.gz && tar -zxvf obsutil_linux_amd64.tar.gz && chmod 755 ./obsutil_linux_amd64_5.7.9/obsutil
      - name: config obsutil
        run: ./obsutil_linux_amd64_5.7.9/obsutil config -i ${{ secrets.OBS_ACCESS_KEY_ID }} -k ${{ secrets.OBS_ACCESS_KEY_SECRET }} -e https://obs.cn-north-4.myhuaweicloud.com
      - name: upload docs by obsutil
        run: ./obsutil_linux_amd64_5.7.9/obsutil cp ./api/docs/index.html obs://open-read/clickvisual/api/index.html -f -r
      - name: create commit
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          delete-branch: true
          commit-message: 'docs: eapi'
          title: eapi
